const state = {
  shopInfo: {},
  token: "",
  invoiceType: 0,
  personType: 1,
  isOpenInvoice: false,
  delivery: "平邮",
  vueModel: {},
  initRouterPath: "",
  penddingPay: false,
  showDeleteButton: false,
  platform: "",
  shopGoodsCartIds: {},
  servicePackage: false,
  servicePackageId: "",
  servicePackageData: {},
  storeId: "",
  orderInfo: {},
  invoiceId: "",
  freightNumber: 0,
  orderIdForInvoice: "",
  paymentSuccessOrderId: "",
  addGoodsCart: false,
  paymentResultPage: 1,
  receiveAddress: {},
  totalPrice: 0,
  totalValue: 0,
  paymentMethod: 1,
  orderConfirmInitStatus: false,
  hasContact: false,
  paymentResultOrderId: "",
  isCanSelectPay: false
};
export default state;
